### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [tlaplus-community/tree-sitter-tlaplus#123]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `tlaplus` (select `Tree-sitter-ebnf-generator-TlaPlus` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by ahelwer** [comment]
Thanks!
