### ISSUE TITLE
PlusCal support

### ISSUE THREAD

**Issue by ahelwer** [tlaplus-community/tree-sitter-tlaplus#31]
Currently PlusCal code just sits undetected, unparsed, and unhighlighted in its block comment. It's an important part of TLA+ and should be supported, either directly in the grammar or via injection of a PlusCal-specific grammar.

**Comment by susliko** [comment]
Hey @ahelwer 👋🏻 
I'd love to contribute the PlusCal grammar to tree-sitter, but haven't decided which way to choose:
1. a. Make a separate repository for PlusCal with a partial copy of the TLA+ grammar for expressions and definitions
    b. Inject PlusCal grammar into TLA+ block comments like this:
```
# injection.scm
((block_comment
 (block_comment_text) @injection.content)
 (#set! injection.language "pluscal"))
```

2. Put PlusCal grammar right behind TLA+ grammar. I've tried this option, putting newly added rules to the `extras` block
```
  extras: $ => [
    /\s|\r?\n/,
    $.comment,
    $.pcal_algorithm,
    $.block_comment
  ],
```
But it seems not to work, since all PlusCal code is still recognized as `block_comment` (however works well if `block_comment` is just removed from extras)

I wonder if you have any ideas on this or can highlight some pitfalls

**Comment by ahelwer** [comment]
Hi @susliko! Very happy to hear someone wants to build a pluscal grammar. My thoughts are split on this (I also admit not knowing pluscal very well compared to TLA+). I understand that pluscal code can itself contain basically any TLA+ construct, including conjunction/disjunction lists ("jlists") and maybe even proofs. It's hard to know for sure; I've [asked on the google group](https://groups.google.com/g/tlaplus/c/eJzZ2Vr4eUY/m/q_gRAGvqCAAJ) for the official pluscal grammar resources but nobody has yet pointed them out. Parsing jlists and proofs were by far the most difficult part of writing this grammar since they are context-sensitive; I had to write an external scanner, which you can see [here](https://github.com/tlaplus-community/tree-sitter-tlaplus/blob/main/src/scanner.cc). So if these can indeed be included in pluscal code, it makes sense to add pluscal to this grammar instead of copying the scanner code to a separate project and having to deal with keeping it in sync given any fixes or changes. The prefix/infix/postfix operator grammar rules are also nontrivial.

On the other hand it would be nice to have an independent pluscal grammar for the possible future happy day where pluscal lives as its own language instead of as part of a weird partially-auto-generated file. It also is an ideal candidate for the injection feature, as you pointed out. We would have to make a somewhat minor modification to the TLA+ external scanner so that it differentiates pluscal sections from block comments, giving you a rule name for easy injections (the reason your `extras` solution didn't work is because the external scanner takes lexical precedence over rules that live in the grammar). There is apparently also some capability to [extend grammars](https://github.com/tree-sitter/tree-sitter/issues/645) which I haven't yet looked into, which could be used to avoid the code duplication problem described above.

Either way I'm happy to answer any questions you have about tree-sitter itself and how it works, and accept any PRs you file as long as they (1) don't bloat the generated code *too much more* (it's already at like 30 MB) and (2) have a good set of tests.

**Comment by susliko** [comment]
Thanks for the response and willingness to help!

Fortunately, PlusCal has a BNF (page 60-62 of the [p-manual](https://lamport.azurewebsites.net/tla/p-manual.pdf)), which relies on TLA+ grammar, e.g.:
```
<Defs> ::= A sequence of TLA+ definitions not containing a PlusCal
reserved word or symbol.
```
And I've made a [sketch](https://gist.github.com/susliko/371d1217836ee272e18703d7caba62d9) of it in terms of tree-sitter.

Honestly, I'm a bit confused about the necessity of external scanner to support nested comments.
I'll dive into this and will let you know in case of any progress :)

Also, do you know about any ongoing efforts on making PlusCal a self-sustained language?

**Comment by ahelwer** [comment]
@susliko I see you've found [this issue](https://github.com/tlaplus-community/tree-sitter-tlaplus/issues/15) documenting using the external scanner for block comments. This was about five months ago so I don't thoroughly remember all the problems that come with trying to write it in the grammar itself; I found [this discussion post by me](https://github.com/tree-sitter/tree-sitter/discussions/1252) which might expand on it more. My vague impression is that it might be *possible* to do it in the grammar but by that point I was so used to writing external scanner code I just went ahead and implemented it there. I also added the ability to look ahead and include multiple contiguous block comments as a single block comment, which helps with code folding in neovim.

There aren't really any ongoing efforts at changing pluscal's interaction with TLA+, beyond my vague desire to do so. It's fairly far down my own list of priorities for TLA+ and would probably be part of a larger effort to move beyond the java tools.

**Comment by ahelwer** [comment]
@susliko what do you think would be an ideal parse tree for the pluscal block in the TLA+ grammar? Something like:
```
(block_comment
  (pluscal_algorithm)
)
```
where `pluscal_algorithm` includes and is delimited by `--algorithm`/`end algorithm`?

**Comment by susliko** [comment]
@ahelwer as far as I have tested, the PlusCal transpiler expects algorithm name do be the same as module name and just ignores others. So, only one algorithm per file is allowed
Before and after the algorithm definition (but not in the body) there might be any kind of text.
This is a correct spec:
```
---- MODULE simple ----
EXTENDS TLC, Integers
(* 
foo
(* bar *)
--algorithm simple
variables alice_account = 10, bob_account = 10, money = 5;
begin
A: alice_account := alice_account - money;
B: bob_account := bob_account + money;
end algorithm; 
quux
*)
====
```
Considering this, it seems reasonable to implement `pluscal_algorithm`  as a part of `block_comment` on par with `block_comment_text`

**Comment by susliko** [comment]
Submitted a draft PR https://github.com/tlaplus-community/tree-sitter-tlaplus/pull/45
