### ISSUE TITLE
Failing tests with latest tree-sitter versions

### ISSUE THREAD

**Issue by susliko** [tlaplus-community/tree-sitter-tlaplus#46]
At the moment CI piplines use the tree-sitter [fork](https://github.com/tlaplus-community/tree-sitter), which is at version 0.20.0
Running tests on `main` branch via latest versions (0.20.1 and 0.20.2 tested) of tree-sitter results in a few failing tests:
![image](https://user-images.githubusercontent.com/15569000/148544647-64eff0c9-e75f-4b29-9d7c-1dec5c12933f.png)
![image](https://user-images.githubusercontent.com/15569000/148544709-72665b6b-9190-4f4d-b26a-50d4178593d3.png)
Steps to reproduce:
```
cargo install tree-sitter-cli
tree-sitter generate
tree-sitter test
```

**Comment by ahelwer** [comment]
Huh, wonder how this wasn't caught by CI. I noticed this on my mac a couple weeks ago but thought it was just a local thing. Will look into it.

**Comment by susliko** [comment]
I've tested multiple combinations locally on Linux:
| Generate by | Test by | Test result |
| --- | --- | --- |
|fork|fork|ok|
|fork|upstream|error|
|upstream|fork|error|
|fork|upstream|error|

So, even with the fork-generated grammar latest tree-sitter versions fail to parse some specs with `disj_list` and `conj_list` correctly

**Comment by ahelwer** [comment]
The more surprising thing here is that grammars generated with upstream fail on fork. The `get_column` changes are present in the runtime tree-sitter C library, not the generated code. I will do the following:

- Rebase fork changes on latest tree-sitter release and create another fork release
- Actually get around to writing good tests for the `get_column` changes so I can merge them with upstream

**Comment by susliko** [comment]
>he more surprising thing here is that grammars generated with upstream fail on fork

Ah, that's my copy-paste fault. Sorry for that

**Comment by susliko** [comment]
Neovim [ts playground](https://github.com/nvim-treesitter/playground) also shows the behavior described above.
Syntax highlighting is broken as well
![image](https://user-images.githubusercontent.com/15569000/148557800-52cae284-1ddd-4a7c-bcee-b308c68a9e4b.png)
Neovim

**Comment by ahelwer** [comment]
If you would believe it, I had to hack together a fork of neovim using my tree-sitter fork for the demo lol: https://github.com/tlaplus-community/neovim

**Comment by ahelwer** [comment]
Required changes have been merged into upstream tree-sitter and a new release was issued yesterday. Now we are just waiting for the [tree-sitter-cli](https://www.npmjs.com/package/tree-sitter-cli) NPM module to be updated; see https://github.com/tree-sitter/tree-sitter/issues/1613

**Comment by clason** [comment]
Neovim (nightly) already has tree-sitter 0.20.3 since yesterday ;)

**Comment by maxbrunsfeld** [comment]
0.20.4 is out on npm.
