### ISSUE TITLE
Handle block comment start/end tokens in strings and single-line comments

### ISSUE THREAD

**Issue by ahelwer** [tlaplus-community/tree-sitter-tlaplus#83]
SANY correctly parses this, but the grammar does not:
```tla
---- MODULE Test ----
op == "(*"
====
```
Both SANY and the grammar fail on these cases:
```tla
---- MODULE Test ----
(*op == "*)"*)
=====================
```
```tla
---- MODULE Test ----
(*
\* *)
*)
=====================
```
Ref https://github.com/tlaplus/tlaplus/issues/812

**Comment by ahelwer** [comment]
Another one, this time with a single-line comment inside strings:
```tla
---- MODULE Test ----
op == "\*"
=====================
```

**Comment by ahelwer** [comment]
SANY handles this but this grammar does not; perhaps prior example with single-line comment starting inside string *should* be parsed as a single-line comment.
```tla
---- MODULE Test ----
op == "\\*"
=====================
```

**Comment by ahelwer** [comment]
@susliko would you be able to handle this one if you have time? I'm not entirely sure how all the comment precedence stuff interacts with everything else.

**Comment by susliko** [comment]
@ahelwer Sorry it took a long time to respond! Here's my PR for this issue https://github.com/tlaplus-community/tree-sitter-tlaplus/pull/89
